version: '3.7'
services:
 base: &base
  build: ./
  ports: 
   - "3000:3000"
  volumes:
   - "./app:/app"

 dev:
  <<: *base
  command: /bin/bash -l -c "rails s -b 0.0.0.0"

 test:
  <<: *base
  command: /bin/bash -l -c "bundle exec rspec"

 guard:
  <<: *base
  command: /bin/bash -l -c "bundle exec guard"